### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by hymRedemption** [YangXinlin/sikeio-buyshoes-startkit#1]
```css
.site {
  flex-direction: row;
  height: 100%;
  background-size: cover;
  background-position: center;
}
```
这里的 height 不应该设置成 100%， 如果设置成这样，那么网页的高度只有一个页面的高度
